
## 1. Java中的异常
>Throwable是所有Java程序中错误处理的父类 ，有两种子类：Error和Exception。

>Throwable是所有异常的根，java.lang.Throwable 
Error是错误，java.lang.Error 
Exception是异常，java.lang.Exception
Error：表示由JVM所侦测到的无法预期的错误，由于这是属于JVM层次的严重错误 ，导致JVM无法继续执行，因此，这是不可捕捉到的，无法采取任何恢复的操作，顶多只能显示错误信息。 Error类体系描述了Java运行系统中的内部错误以及资源耗尽的情形.应用程序不应该抛出这种类型的对象(一般是由虚拟机抛出).假如出现这种错误,除了尽力使程序安全退出外,在其他方面是无能为力的。
Exception：表示可恢复的例外，这是可捕捉到的.分为运行时异常,检查性异常.

---
>Java提供了两类主要的异常 :runtime exception和checked exception。

**checked异常**：IO异常，以及SQL异常都是这种异常。 对于这种异常， JAVA编译器强制要求我们必需对出现的这些异常进行catch 。所以，面对这种异常不管我们是否愿意，只能自己去写一大堆catch块去处理可能的异常。 这类异常一般是外部错误，例如试图从文件尾后读取数据等,这并不是程序本身的错误,而是在应环境中出现的外部错误。 (编译时抛出)
**runtime exception 运行时异常**：我们可以不处理。当出现这样的异常时，总是由虚拟机接管。出现运行时异常后，系统会把异常一直往上层抛，一直遇到处理代码。如果没有处理块，到最上层，如果是多线程就由Thread.run()抛出，如果是单线程就被main()抛出。抛出之后，如果是线程，这个线程也就退出了。如果是主程序抛出的异常，那么这整个程序也就退出了。如果不想终止，则必须扑捉所有的运行时异常，决不让这个处理线程退出。(运行时抛出)

>Exception 与 RuntimeException 的区别？
Exception ：受检异常
在编译时就会报错，在调用可能抛出这个异常的方法时，必须显示的使用try..catch...
RuntimeException ：非受检异常
在编译时不会报错，在运行时才会报错，在调用可能抛出这个异常的方法时，不用显示的使用try..catch...
在使用自定义异常时，根据实际的业务要求来决定使用哪个作为父类

## 2. 自定义异常 & 统一异常处理

+ MyException:
```Java
public class MyException extends Exception{

    Integer code;

    public  MyException(){
        super();
    }
    public  MyException(String detailMsg){
        super(detailMsg);
    }

    public  MyException(Integer code, String detailMsg){
        super(detailMsg);
        this.code = code;
    }

    public Integer getCode() {
        return code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }
}
```

+ MyRuntimeException
```Java
public class MyRuntimeException extends RuntimeException{
    Integer code;
    public MyRuntimeException(){
        super();
    }
    public MyRuntimeException(Integer code, String msg){//这里可以将参数改为一个自定义的枚举，比如改为Result中的EType
        super(msg);
        this.code = code;
    }

    public Integer getCode() {
        return code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }
}
```

+ MyExceptionHandler
```Java
@ControllerAdvice
@RestController
public class MyExceptionHandler {

    @ExceptionHandler(Exception.class)
    public Result exceptionHandler(Exception e){
        Result result = null;
        e.printStackTrace();
        if(e instanceof MyException){
            result = Result.serviceException(((MyException) e).code, Result.EType.invalidArguments.getValue());
        }else{
            int index = e.getMessage().lastIndexOf("[");
            result = Result.serviceException(-1, index!= -1?e.getMessage().substring(index + 1,e.getMessage().length()-1).trim():e.getMessage());
        }
        return  result;
    }
    @ExceptionHandler(MyRuntimeException.class)
    public Result myRuntimeExceptionHandler(MyRuntimeException e){
        e.printStackTrace();
        return Result.serviceException(e.getCode(), e.getMessage());
    }
}
```

+ DealService
```Java
@Service
public class DealService {

    public void deal(Integer value) throws MyException {
        if (null == value)
            throw new MyException(-22, "值不能为空！");
    }

    public void deal_2(Integer value) throws MyRuntimeException {
        if (null == value)
            throw new MyRuntimeException(-22, "值不能为空！");
    }

    public void deal_3(Integer value) throws MyException, MyRuntimeException{
        if (null == value)
            throw new MyException(-22, "值不能为空！");
        else if (0 > value)
            throw new MyRuntimeException(-23, "值不能小于0！");

    }
    public void deal_4(Integer value) throws Exception{
        if(0 == value){
            int s = 3 / value;
        }
    }
}
```

+ testController

```Java
@Api(tags = "测试接口", value = "test")
@RestController
@RequestMapping("test")
public class testController {

    @Autowired
    private DealService dealService;


    @GetMapping(value = "exception")
   public Result exception(@RequestParam(required = false) Integer value) {
       Result result;
       try {
           dealService.deal(value);
           result = Result.success();
       } catch (MyException e) {
           result = Result.serviceException(e.getCode(), e.getMessage());
       }
       return result;
   }

   @GetMapping(value = "exception2")
   public Result exception2(@RequestParam(required = false) Integer value) {
       Result result;
       try {
           dealService.deal_2(value);
           result = Result.success();
       } catch (MyRuntimeException e) {
           result = Result.serviceException(e.getCode(), e.getMessage());
       }
       return result;
   }

   @GetMapping(value = "exception3")
   public Result exception3(@RequestParam(required = false) Integer value) throws MyException, MyRuntimeException{
       dealService.deal_3(value);
       return  Result.success();
   }

   @GetMapping(value = "exception4")
   public Result exception4(@RequestParam(required = false) Integer value) throws Exception{
       dealService.deal_4(value);
       return  Result.success();
   }
}
```

+

```Java
@Data
public class Result {
    private int code;
    private String message;
    private Object data;
    private String time = AppConst.sdf_y_s.format(new Date(System.currentTimeMillis())); //public final static SimpleDateFormat sdf_y_s = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");

    public static Result success(){
        Result result = new Result();
        result.code = SType.success.key;
        result.message = SType.success.value;
        return result;
    }
    public static Result success(SType type, Object data){
        Result result = new Result();
        result.code = type.key;
        result.message = type.value;
        result.data = data;
        return result;
    }
    public static Result error(EType type, Object data){
        Result result = new Result();
        result.code = type.key;
        result.message = type.value;
        result.data = data;
        return result;
    }

    public static Result serviceError(){
        Result result = new Result();
        result.code = EType.remoteServiceError.key;
        result.message = EType.remoteServiceError.value;
        return result;
    }
    public static Result serviceError(String error){
        Result result = new Result();
        result.code = EType.remoteServiceError.key;
        result.message = error;
        return result;
    }
    public static Result serviceException(int code, String message){
        Result result = new Result();
        result.code = code;
        result.message = message;
        return result;
    }

    public enum SType {
        /**
         * 操作成功
         */
        success(0,"成功"),
        save(1,"保存成功");
        private Integer key;
        private String value;
        SType(Integer key, String name) {
            this.key = key;
            this.value = name;
        }
        public Integer getKey() {
            return key;
        }
        public void setKey(Integer key) {
            this.key = key;
        }
        public String getValue() {
            return value;
        }
        public void setValue(String value) {
            this.value = value;
        }
    }

    public enum EType {
        /**
         * 操作失败
         */
        fail(-1,"失败"),
        uploadFail(-101, "文件上传失败"),
        serviceCurrentlyUnavailable(-102, "服务不可用"),
        remoteServiceError(-103, "远程服务出错"),
        missingMethod(-104, "缺少方法名参数"),
        invalidFormat(-105, "非法数据格式"),
        missingSignature(-106, "参数为空"),
        invalidSignature(-107, "非法签名"),
        missingRequiredArguments(-111, "缺少必选参数"),
        invalidArguments(-112, "非法的参数"),
        forbiddenRequest(-113, "请求被禁止"),
        parameterError(-114, "参数错误")	,
        accountErros(-115,"账户名不存在，请重新输入"),
        accountRegisted(-116,"账户已注册"),
        captchaErros(-117,"验证码错误"),
        accounOrPwdtErros(-118,"账户名与密码不匹配，请重新输入"),
        accountStop(-156,"该用户已经被停用"),
        notLogin (-121,"用户未登录"),
        notPermissions(-122,"用户没有权限"),
        oldPasswordErros(-123,"原密码错误"),
        entityError(-124,"上传文件的实体对象不匹配"), ;
        private Integer key;
        private String value;
        EType(Integer key, String name) {
            this.key = key;
            this.value = name;
        }
        public Integer getKey() {
            return key;
        }
        public void setKey(Integer key) {
            this.key = key;
        }
        public String getValue() {
            return value;
        }
        public void setValue(String value) {
            this.value = value;
        }
    }
}
```


## Java异常处理之InvocationTargetException
Method.invoke
当被调用的方法的内部抛出了异常而没有被捕获时，将由此异常接收

## Spring MVC传参：Cannot construct instance of xxxxx(no Creators, like default construct, exist)
添加默认构造函数

## "[Ljava.lang.Object; cannot be cast to [Ljava.lang.String;"
```java
List<String> list = new ArrayList();
...
//(String[]) list.toArray(); // throw in here
(String[]) list.toArray(new String[list.size]);
// 在java的api中有两种方法：
// 1.不带参数的toArray()
// 如果不带参数，它会自动new Object[emails.size()],然后在(String[ ])强转，所以就会报错
// 2. 带参数的toArray()
// 在转换的的时候，指定参数(String[])(emails.toArray(new String[ emails.size()])),这样在转换的时候就不会报错了


```
